---
title: "Vis 1"
author: "Chhiring Lama"
date: "2024-09-26"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rnoaa)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())

```


Making our first plot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

We can save and print it later
```{r}
gg_weather_scatterplot <- ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()

gg_weather_scatterplot
```

Check why some rows are missing
```{r}

```


## fancier scatterplots

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.6, size = 0.8) +
  geom_smooth(se = FALSE)
```

Where we define the `aes` matters. The smoothing looks different when used in `geom` where we only define the color grouping only for the scatterplot, the grouping is not global so `geom_smooth` does not recognize this. 
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(alpha = 0.6, size = 0.8, aes(color = name)) +
  geom_smooth(se = FALSE)
```

Use facet
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(alpha = 0.6, size = 0.8, aes(color = name)) +
  geom_smooth(se = FALSE) +
  facet_grid(.~name)
```
